### ISSUE TITLE
test checks for non-existent file

### ISSUE THREAD

**Issue by karimsa** [mlucool/gulp-jsdoc3#19]
This is a part of the log from travis-ci:

```
Unhandled rejection AssertionError: expected [Error: ENOENT: no such file or directory, open '/tmp/tmp-2733MA0IclnLiPOp/testFile.js.html'] to not exist
    at gulp-jsdoc_spec.js:118:21
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/build/mlucool/gulp-jsdoc3/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I ran this a few times in a few different environments (both before/after fixing #17), and it seems that jsdoc during this test does not create 'testFile.js.html'. I believe this is because there is no layout template for individual source files. For some reason, the failure of this assertion does not stop deployment on travis (or even get caught by istanbul).

Is the file supposed to be generated? Or perhaps it wouldn't be generated under this layout?

**Comment by mlucool** [comment]
The travis CI passed because: https://github.com/mlucool/gulp-jsdoc3/blob/master/test/gulp-jsdoc_spec.js#L118 this should have called: cb(err);

Looking at this test, I think its just making a wrong expectation how this plugin works. I missed this during the code review. Per https://github.com/mlucool/gulp-jsdoc3#notes it does not have good support for passing data elsewhere. Instead I would restructure it to how other tests used done (e.g.) https://github.com/mlucool/gulp-jsdoc3/blob/master/test/gulp-jsdoc_spec.js#L51

**Comment by karimsa** [comment]
I thought that too, but shouldn't `expect()` throw an assertion error that should stop the test from continuing?

I changed it to that originally, but that doesn't make sense either. When you were writing the tests, you intended for that test to not pass a callback to the plugin. Which is why you had to have an alternate way to check for errors.

I have refactored this in PR #20.

**Comment by mlucool** [comment]
Fixed
