### ISSUE TITLE
Gulp 4.0 alpha 2 support

### ISSUE THREAD

**Issue by ZiperRom1** [mlucool/gulp-jsdoc3#21]
The task fails on gulp 4.0 alpha 2

```
[11:17:55] Starting 'jsDoc'...
[11:17:55] Starting 'jsdoc_generation'...
[11:17:56] fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\prog\ziperrom1.github.io\awesomechatroom-doc\jsDoc\lib_navigation%0A%0AHandle%20the%20current%20page%20attributes%20such%20as%20the%20page%20title%20or%20the%20page%20parameters.%0AIt%20loads%20pages%20by%20hide%20_%20show%20pages%20DOM%20classes%20elements%20to%20use%20a%20Single%20Page%20Web%20pattern%20and%20avoiding%20browser%0Apage%20reloading%20to%20keep%20the%20WebSocket%20connection%20alive.%0AIt%20load%20pages%20on%20hashchange%20event%20and%20detect%20the%20page%20to%20load%20by%20parsing%20the%20hash.module_.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at generate (C:\prog\awesomechatroom\static\node_modules\ink-docstrap\template\publish.js:262:6)
    at Object.exports.publish (C:\prog\awesomechatroom\static\node_modules\ink-docstrap\template\publish.js:783:9)
    at Object.module.exports.cli.generateDocs (C:\prog\awesomechatroom\static\node_modules\jsdoc\cli.js:430:39)
    at Object.module.exports.cli.processParseResults (C:\prog\awesomechatroom\static\node_modules\jsdoc\cli.js:383:20)
    at module.exports.cli.main (C:\prog\awesomechatroom\static\node_modules\jsdoc\cli.js:227:14)
    at Object.module.exports.cli.runCommand (C:\prog\awesomechatroom\static\node_modules\jsdoc\cli.js:180:5)
    at C:\prog\awesomechatroom\static\node_modules\jsdoc\jsdoc.js:103:9
    at Object.<anonymous> (C:\prog\awesomechatroom\static\node_modules\jsdoc\jsdoc.js:104:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

[11:17:56] JSDoc returned with error code: 1
[11:17:56] 'jsdoc_generation' errored after 1.38 s
```

**Comment by ZiperRom1** [comment]
It seems it is a jsDoc error so not relative to the gulp plugin, apologize i'm investigating...

**Comment by ZiperRom1** [comment]
`@module` tag should be place at the the very end of the documentation first docBlock or it takes all the description (even with 2 EOL after the tag) and breaks the writing path.
