### ISSUE TITLE
Blank license field causes error in JSdoc

### ISSUE THREAD

**Issue by caraya** [mlucool/gulp-jsdoc3#23]
When running gulp-jsdoc3 I'm getting the following error: `ERROR: The @license tag requires a value. File: lunr.min.js, line: 1`. I see that the license field is indeed blank but can't find the source of the file being copied to the output directory to make a pull request. 

This appears to be an issue in the lunr repository but I'm not sure if it's gulp's handling of JSdoc or somehting else. 

I've filed olivernn/lunr.js#217 against the lunr repository for them to fix the issue upstream

**Until this is fixed, where do I pull the source for lunr so I can manually remove the tag?**

**Comment by caraya** [comment]
The error has been fixed in Lunr's repo. Is it possible to update the dependency in JSDoc?

**Comment by mlucool** [comment]
There is no dependency here for lunr as far as I can tell. If you update your code for the template it should work.

**Comment by caraya** [comment]
I've reinstalled gulp-jsdoc and jsdoc. I keep getting the same error. 

I believe that lunr implements search on the theme used by the plugin but I can't find if it's bundled with this project or loaded as a dependency. 

This is the error:

```
[15:33:18] carlos@Rivendell minimal-transpiler 4267$ gulp jsdoc
(node:87595) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[15:44:44] Using gulpfile ~/code/minimal-transpiler/gulpfile.js
[15:44:44] Starting 'jsdoc'...
[15:44:49] ERROR: The @license tag requires a value. File: lunr.min.js, line: 1

[15:44:50] JSDoc returned with error code: 1
[15:44:50] 'jsdoc' errored after 6.05 s
[15:44:50] Error: JSDoc closed with error code: 1
    at ChildProcess.<anonymous> (/Users/carlos/code/minimal-transpiler/node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js:129:32)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by mlucool** [comment]
It is not bundled with this project

**Comment by caraya** [comment]
It doesn't help me troubleshoot the issue but since it's not bundled with the project it's no use keep the issue open.

**Comment by toutpt** [comment]
This has nothing to do with jsdoc but with docstrap. I'm currently working on a pull request https://github.com/docstrap/docstrap/

**Comment by caraya** [comment]
@toutpt thanks, that's all I needed to know...
