### ISSUE TITLE
Getting issue while generating docs

### ISSUE THREAD

**Issue by MandeepKalkhanda** [mlucool/gulp-jsdoc3#43]
Error: JSDoc closed with error code: 1
    at ChildProcess.<anonymous> (node_modules\gulp-jsdoc3\dist\gulp-jsdoc.js:145:32)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by AndrewGuenther** [comment]
Can you provide a bit more context? Would you mine sharing what your gulpfile and jsdoc config look like?

**Comment by MandeepKalkhanda** [comment]
@AndrewGuenther 

I am using the simplest gulp task given in npm package help.
Below is the gulp file.

return gulp.src([`${sourceDir}/js/modules/**/*.js`], {read: false})
      .pipe(plugins.jsdoc3(cb));

Not using jsDoc config.

**Comment by AndrewGuenther** [comment]
Do you get this error consistently? Is there any other error output? 

This means that JSDoc itself is failing somewhere, so I'm surprised that there isn't any other output.

**Comment by MandeepKalkhanda** [comment]
@AndrewGuenther 

Yes I am getting this consistently there is some output error but that some to be related to Commenting of the method.

Below is the one.
[01:59:40] ERROR: Unable to parse a tag's type expression for source file ...file_path
 setScalingValue - Setter for scaling.": Expected "|" but "-" found.M.{

**Comment by AndrewGuenther** [comment]
Ah, that means there is a syntax error in your JSDoc syntax.

**Comment by MandeepKalkhanda** [comment]
@AndrewGuenther 

Even after removing all syntax errors, exception is thrown.

[02:06:38] Error: task completion callback called too many times
    at finish (..\node_modules\
orchestrator\lib\runTask.js:15:10)
    at cb (..\orch
estrator\lib\runTask.js:29:3)
    at tryCatcher (..\node_modu
les\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (..\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (..\node_modules\bluebird\js\release\promise.js:564:21)
    at Promise._settlePromise0 (..\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (..\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (..\no
de_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (..\n
ode_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (..\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by AndrewGuenther** [comment]
What is the callback you're passing in in your gulpfile? You're not using gulp.dest anywhere are you?

@mlucool, you got any ideas on this one?

**Comment by MandeepKalkhanda** [comment]
function generateDocs(cb) {
    return gulp.src([`${sourceDir}/js/modules/**/*.js`], {read: false})
      .pipe(plugins.jsdoc3(cb));
  }

  gulp.task('docs.generate', generateDocs);

this is the complete gulp task file I am using. Out is generated in docs/gen folder.

**Comment by mlucool** [comment]
Nothing screams out. Can you try to reproduce with something you can share? Or maybe share the output of running it with the environment variable: ```DEBUG='gulp-jsdoc3'```

**Comment by MandeepKalkhanda** [comment]
[22:02:53] Starting 'docs.generate'...
  gulp-jsdoc3 Config:
{
  "tags": {
    "allowUnknownTags": true
  },
  "opts": {
    "destination": "./docs/gen"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false,
    "default": {
      "outputSourceFiles": true
    },
    "path": "ink-docstrap",
    "theme": "cerulean",
    "navType": "vertical",
    "linenums": true,
    "dateFormat": "MMMM Do YYYY, h:mm:ss a"
  }
} +0ms
  gulp-jsdoc3 Documenting files: list of project js files... +62ms
[22:02:53] Finished 'docs.generate' after 176 ms
  gulp-jsdoc3 ..\node_modules\j
sdoc\jsdoc.js -c ..\AppData\Local\Temp\tmp-4680prNmyCQ321gH.tmp -t
 ..\node_modules\ink-docstrap\t
emplate +31ms
[22:03:00] Documented 138 files!
[22:03:00] 'docs.generate' errored after 6.67 s
[22:03:00] Error: task completion callback called too many times
    at finish (...\node_modules\
orchestrator\lib\runTask.js:15:10)
    at cb (...\node_modules\orch
estrator\lib\runTask.js:29:3)
    at tryCatcher (...\node_modu
les\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (...\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:564:21)
    at Promise._settlePromise0 (...\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (..\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (...\no
de_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (...\n
ode_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (...\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

...>

Output with DEBUG.

**Comment by mlucool** [comment]
This means the cb you pass in is getting called more than once. From the snippit you gave, it seems that nothing you are doing would cause this.

Can you edit ```node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js```: as follows:
```
            debug('Documenting files: ' + jsdocConfigClone.source.include.join(' '));
            _fs2.default.writeFile(tmpobj.name, JSON.stringify(jsdocConfigClone), 'utf8', function (err) {
+            debug(JSON.stringify(jsdocConfigClone))
````
Then rerun with debug and use the output with the above command that was printed:
```
 ..\node_modules\jsdoc\jsdoc.js -c ..\AppData\Local\Temp\tmp-4680prNmyCQ321gH.tmp -t ..\node_modules\ink-docstrap\template
```
Where you would sub a saved version of the new output for  `..\AppData\Local\Temp\tmp-4680prNmyCQ321gH.tmp`

Basically, my goal is to check how this runs without the gulp plugin.

**Comment by MandeepKalkhanda** [comment]
@mlucool 
my task completed without exceptions if I don't pass the cb in jsdocs3.

Thanks for your support.

**Comment by mlucool** [comment]
Ok - closing as a no op here
